@startuml

object "c1:Course" as c1 {
    name = "CS5800 - Advanced Software Engineering"
}
object "c2:Course" as c2 {
    name = "CS6000-Duality"
}

object "c1Instructor:Instructor" as c1ins{
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
}

object "c1Instructor:Instructor" as c1ins{
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
}

object "c1TextBook:TextBook" as c1tb{
    title = "CleanCode:A Handbook of Agile Software Craftsmanship"
    author = "Robert Cecil Martin"
    publisher = "Pearson"
}

object "c2Instructor1:Instructor" as c2ins1{
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
}

object "c2Instructor2:Instructor" as c2ins2{
    firstName = "Hao"
    lastName = "Ji"
    officeNumber = "8-42"
}

object "c2TextBook1:TextBook" as c2tb1{
    title = "CleanCode:A Handbook of Agile Software Craftsmanship"
    author = "Robert Cecil Martin"
    publisher = "Pearson"
}

object "c2TextBook2:TextBook" as c2tb2{
    title = "Me Talk Pretty One Day"
    author = "David Sedaris"
    publisher = "Back Bay Books"
}

c1 o-- c1ins
c1 o-- c1tb
c2 o-- c2ins1
c2 o-- c2ins2
c2 o-- c2tb1
c2 o-- c2tb2

@enduml